/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SinglePlayerImport } from './routes/single-player'
import { Route as MultiPlayerImport } from './routes/multi-player'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SinglePlayerRoute = SinglePlayerImport.update({
  id: '/single-player',
  path: '/single-player',
  getParentRoute: () => rootRoute,
} as any)

const MultiPlayerRoute = MultiPlayerImport.update({
  id: '/multi-player',
  path: '/multi-player',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/multi-player': {
      id: '/multi-player'
      path: '/multi-player'
      fullPath: '/multi-player'
      preLoaderRoute: typeof MultiPlayerImport
      parentRoute: typeof rootRoute
    }
    '/single-player': {
      id: '/single-player'
      path: '/single-player'
      fullPath: '/single-player'
      preLoaderRoute: typeof SinglePlayerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/multi-player': typeof MultiPlayerRoute
  '/single-player': typeof SinglePlayerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/multi-player': typeof MultiPlayerRoute
  '/single-player': typeof SinglePlayerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/multi-player': typeof MultiPlayerRoute
  '/single-player': typeof SinglePlayerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/multi-player' | '/single-player'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/multi-player' | '/single-player'
  id: '__root__' | '/' | '/multi-player' | '/single-player'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MultiPlayerRoute: typeof MultiPlayerRoute
  SinglePlayerRoute: typeof SinglePlayerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MultiPlayerRoute: MultiPlayerRoute,
  SinglePlayerRoute: SinglePlayerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/multi-player",
        "/single-player"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/multi-player": {
      "filePath": "multi-player.ts"
    },
    "/single-player": {
      "filePath": "single-player.ts"
    }
  }
}
ROUTE_MANIFEST_END */
