networks:
  wordle:

services:
  api:
    command: ./wordle
    container_name: wordle.api
    image: api:latest
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - GO_ENV=${GO_ENV:-production}
    networks:
      - wordle
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${PORT:-8080}:8080" # default port is 8080
    environment:
      - GO_ENV=${GO_ENV:-production}
      - TZ=Asia/Hong_Kong
  db:
    container_name: wordle.db
    image: db:latest
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: on-failure
    networks:
      - wordle
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Hong_Kong